name: Build Binary Distribution Daily

on:
  schedule:
    - cron: '0 4 * * *'  # 每天北京时间时间中午12点
  workflow_dispatch:

jobs:
  update-file:
    runs-on: windows-latest

    steps:
      # 检出代码仓库
      - name: Check out the repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 安装所需的依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行你的 Python 脚本
      - name: Start Building Via Nuitka
        run: |
          cd Plain_Craft_Launcher_2
          .\build.cmd
          
      # 配置 Git 推送
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 内置的 Token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build new binary distribution for Application.py."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PCL-Community/PCL2-Python.git HEAD:main
